name 'dannykansas-stackdriver'
version '1.2.0'
source 'git@github.com:dannykansas/puppet-stackdriver-agent.git'
author 'Danny Fowler'
description 'Puppet module to install and configure stackdriver-agent on Debian, RedHat, and Windows'
project_page 'https://github.com/maverixbio/puppet-stackdriver-agent'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'puppetlabs/registry', '>= 1.0.0'
dependency 'joshcooper/powershell', '>= 0.0.6'
